# Generated by Django 2.2.7 on 2019-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
