# Generated by Django 2.2.7 on 2019-12-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achievement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Achievement'),
            preserve_default=False,
        ),
    ]
