# Generated by Django 2.2.7 on 2019-12-06 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='achievement',
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
