# Generated by Django 2.2.7 on 2019-12-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191225_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
