# Generated by Django 2.2.7 on 2019-12-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('costs', models.IntegerField()),
                ('debts', models.IntegerField()),
                ('assets', models.IntegerField()),
                ('capital', models.IntegerField()),
                ('date_of_day', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
