# Generated by Django 3.0.2 on 2020-01-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('costs', models.IntegerField(blank=True, null=True)),
                ('debts', models.IntegerField(blank=True, null=True)),
                ('assets', models.IntegerField(blank=True, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('date_of_day', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
