# Generated by Django 3.0.2 on 2020-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20200109_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointa',
            name='safety_pillow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='assets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='capital',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='date_of_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='debts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointa',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
